### ISSUE TITLE
你好，很期待你的solana笔记！

### ISSUE THREAD

**Issue by first-giver** [kun-g/solana-notes#1]

**Comment by first-giver** [comment]
你好，我最近也在学习solana，希望能和你一起完成这个repo，可以吗

**Comment by first-giver** [comment]
希望可以加个微信：stargaze111，期待与你一起合作，哈哈

**Comment by kun-g** [comment]
> 希望可以加个微信：stargaze111，期待与你一起合作，哈哈

加你了，你没通过 
你可以直接推PR过来
